[profile.default]
solc = '0.8.20'
out = 'out'

remappings = [
  "@openzeppelin/=lib/@openzeppelin/contracts/"
]

[fuzz]
runs = 5_000
max_test_rejects = 0

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = false
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'all'
wrap_comments = true